### ISSUE TITLE
Archives lacking a metadata attribute in the archive element fail to be read

### ISSUE THREAD

**Issue by nickynicolson** [BelgianBiodiversityPlatform/python-dwca-reader#51]
In the [DC spec](http://rs.tdwg.org/dwc/terms/guides/text/index.htm#metafile) the metadata attribute in the archive element is not listed as required, but reading an archive without a metadata element fails.
_[Note: is this DC spec current? If not please add a comment with a pointer to the current spec and I'll update the issue as required.]_

Example archive without metadata element in the archive attribute (in meta.xml): http://zingiberaceae.e-monocot.org/dwca.zip 

Error is thrown in `ArchiveDescriptor` in the file `dwca\descriptors.py`. As this method is reading from `meta.xml` (itself hardcoded as a deafult) it seems reasonable to try to use a default of `meta.xml` if the metadata attribute is missing.

**Comment by niconoe** [comment]
Thanks @nickynicolson !

I'm currently in the process of adding support from other kind of archives, and this is really helpful since it's closely related.

- I'm planning to support cases 1 and 2 described in the table of page 2 in [Darwin Core Archive Format, Reference Guide to the XML Descriptor File](http://www.gbif.org/resource/80639).
- When an Archive lacks a Metafile, it will try to find metadata in a file name EML.xml. If no EML file is present, we assume there's no metadata in the archive.

The case you suggest is a bit different: we do have a metafile, but it doesn't reference any metadata file. I think the best solution in that case is to just gracefully set `dwca.metadata`to `None`.

Another option would be to also use a default of `EML.xml`, but according to the DC spec you mentioned, there's no default value for this attribute.

Do you agree with this course of action? I think by all this, we'll support a whole new range of archives.

BTW, I often have doubts about the standards when discussing such topics, so I've opened a wiki page at https://github.com/BelgianBiodiversityPlatform/python-dwca-reader/wiki/Things-to-clarify-about-the-standards to collect such questions, that may be useful to report later. Don't hesitate if you want to contribute :)

**Comment by nickynicolson** [comment]
Thanks @niconoe - and the wiki page is a good idea, I'll use that.
