### ISSUE TITLE
conda repository version is almost 7 years out-of-date

### ISSUE THREAD

**Issue by pjgoodall** [BelgianBiodiversityPlatform/python-dwca-reader#85]
Hi,
[https://anaconda.org/auto/python-dwca-reader](https://anaconda.org/auto/python-dwca-reader) points to `BelgianBiodiversityPlatform/python-dwca-reader` as its source. The version in anaconda is 6 years and 7 months old. Apart from its senility, it doesn't load because there is no provider of lxml

`conda` is a very popular python environment manager, and it would be *a good thing* if the `dwca_reader` was ready to use there.

Cheers,
--Peter G

**Comment by pjgoodall** [comment]
Would [bioconda](https://bioconda.github.io/) be a good option for getting dwca-reader in good shape on the conda platform?

**Comment by niconoe** [comment]
Thanks for the report, @pjgoodall!

I actually had no idea there was a version available in anaconda since I mostly use pip/virtualenv myself. It was probably uploaded there by someone else.

But you're absolutely right that it would be a good thing, and I'm always willing to make that tool easier to install and use.

I have no experience building conda packages, but I guess it shouldn't be too complicated (current-python-dwca reader doesn't need `lxml` anymore since a long time, which make it easier to install/package).

So, I'll have a look into this. Unfortunately I cannot guarantee a deadline :)

Thanks again for pointing the issue, that's very much appreciated!

**Comment by pjgoodall** [comment]
Hi Nicolas,

Biconda seems to be setup for ease of use. I started looking at it when I
made the report. I think it’s designed to allow several alternative
publishing processes. Some look as simple as encapsulating a pip install in
a shell script,  or I think  you can go the full conda experience with
explicit dependencies. I believe it it will auto-publish new releases as
well.

Cheers,
—Peter Goodal

**Comment by JWCook** [comment]
I'm not too familiar with bioconda, but I could help get this on [conda-forge](https://conda-forge.org/) if that would work for you?

**Comment by niconoe** [comment]
Any option that would help conda users easily install the package would be very welcome!

**Comment by JWCook** [comment]
Submitted a PR for this here: https://github.com/conda-forge/staged-recipes/pull/14969

**Comment by pjgoodall** [comment]
Great - thanks very much

**Comment by JWCook** [comment]
Done. You can now install this package with `conda install -c conda-forge python-dwca-reader`.
* Feedstock: https://github.com/conda-forge/python-dwca-reader-feedstock
* Package info: https://anaconda.org/conda-forge/python-dwca-reader

@niconoe Conda builds will automatically get triggered whenever you release to PyPI, so there's nothing else you need to do for now. If for some reason you or someone else needs to make manual changes to the conda recipe, you can [add yourself as a maintainer](https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list) by opening a PR on the feedstock repo.
