### ISSUE TITLE
InvalidArchive: The descriptor references a non-existent field (index=17)

### ISSUE THREAD

**Issue by MattStata** [BelgianBiodiversityPlatform/python-dwca-reader#88]
Hello, I have downloaded a number of simple archives from GBIF, mostly per-genus, and I'm trying to parse them with a Python script.  Most of them open and parse properly but some throw an InvalidArchive error, referencing index 17.  This occurs at the following point in my script:

with DwCAReader(genus+'.zip') as dwca:
        for core_row in dwca:

I've tried downloading these again, I've tried unzipping them (which works fine) and rezipping as zip or tgz, and the same error still persists.  Can you please suggest anything that I might do to fix this?

**Comment by niconoe** [comment]
Thanks!

I'll investigate deeper later, but I think a more robust way to work would be to download the data as Darwin Core Archives, rather than the "simple" option  provided by GBIF. python-dwca-reader is especially build to work with full Darwin Core Archives. The Darwin Core Archive specifications also allow "simple archives" (that should work here too, but a bug. is always possible), but I'm not sure how GBIF's simple download are compatible with those simple archives specifications.

Sorry for the confusion, those standards aren't as clearly defined as I'd like. Don't hesitate to tell me if it works better with the Darwin Core Archive download!

**Comment by MattStata** [comment]
The only reason I didn't download the larger Darwin Core Archive files was that I had so many to download and those took quite a bit longer, and the simple archives seemed to contain everything I needed.  I'm simply trying to parse all of these to identify recent herbarium collections of key species in these groups and sort them by institution so that I can see which institutions have the best collections to request loans/samples from.  I think that my approach of dropping the problem rows that I developed after my initial post is probably fine for my purposes, but hopefully the info I've provided here can help you figure out why this error is occurring and improve things!  I will make an attempt with one of the problem ones as a Darwin Core Archive when I have some time later and let you know what happens, also.

**Comment by niconoe** [comment]
I've finally had a proper look, but it appears it's a complex/messy case due to double quotes characters appearing randomly in data fields. Due to the fact that it's a simple CSV file (as opposed to a proper DwC-A) we have to "sniff" the details of the files using Python facilities, and for some reason Python thinks the double quote is used to quote fields, the corresponding line is therefore not properly split.

I'm not sure there's a better solution TBH, those sniffing methods are always imperfect, but it's the best we can do with that kind of input.
